package frc.ntclient;

//import java.io.File;
//import java.io.FileWriter;
//import java.io.IOException;
//import java.util.ArrayList;
//import java.util.List;
//import java.util.Map;
//import java.util.stream.Collectors;
//import java.util.HashMap;

import org.opencv.core.*;
//import org.opencv.core.Core.*;
//import org.opencv.features2d.FeatureDetector;
//import org.opencv.imgcodecs.Imgcodecs;
//import org.opencv.imgproc.*;
//import org.opencv.objdetect.*;

/**
* GripPipeline class.
*
* <p>An OpenCV pipeline generated by GRIP.
*
* @author GRIP
*/
public class GripPipeline {

	//Outputs
	private Mat cvAbsdiffOutput = new Mat();

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	/**
	 * This is the primary method that runs the entire pipeline and updates the outputs.
	 */
	public void process(Mat source0, Mat source1) {
		// Step CV_absdiff0:
		Mat cvAbsdiffSrc1 = source0;
		Mat cvAbsdiffSrc2 = source1;
		cvAbsdiff(cvAbsdiffSrc1, cvAbsdiffSrc2, cvAbsdiffOutput);
	}

	/**
	 * This method is a generated getter for the output of a CV_absdiff.
	 * @return Mat output from CV_absdiff.
	 */
	public Mat cvAbsdiffOutput() {
		return cvAbsdiffOutput;
	}

	/**
	 * Calculates the absolute difference between two Mats.
	 * @param src1 the first Mat
	 * @param src2 the second Mat
	 * @param out the Mat that is the absolute difference between the two Mats
	 */
	private void cvAbsdiff(Mat src1, Mat src2, Mat out) {
		Core.absdiff(src1, src2, out);
	}
}